SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "-03:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES cp1256 */;

--
-- Base de Dados: `OrganizzaEstudio`
--
CREATE DATABASE IF NOT EXISTS `OrganizzaEstudio` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci;
USE `OrganizzaEstudio`;

DROP TABLE IF EXISTS `FUNCIONARIO`;
CREATE TABLE IF NOT EXISTS `FUNCIONARIO` (
  `CdFuncionario` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cpf` VARCHAR(18) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Cep` VARCHAR(8) NULL,
  `Endereco` VARCHAR(150) NULL,
  `EnderecoNumero` VARCHAR(20) NULL,
  `Uf` CHAR(2) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Bairro` VARCHAR(50) NULL,
  `Telefone` VARCHAR(14) NULL,
  `Celular` VARCHAR(14) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `DataNascimento` DATE NULL,
  PRIMARY KEY(`CdFuncionario`),
  UNIQUE KEY (`Cpf`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;

DROP TABLE IF EXISTS `SERVICO`;
CREATE TABLE IF NOT EXISTS `SERVICO` (
  `CdServico` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Valor` DECIMAL(19,4) NOT NULL,
  `Descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY(`CdServico`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;


CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `CdCliente` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `CpfCnpj` VARCHAR(18) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `RazaoSocial` VARCHAR(255) NULL,
  `InscricaoEstadual` VARCHAR(18) NULL,
  `CEP` VARCHAR(8) NULL,
  `Endereco` VARCHAR(150) NOT NULL,
  `EnderecoNumero` VARCHAR(20) NULL,
  `Uf` CHAR(2) NULL,
  `Cidade` VARCHAR(50) NULL,
  `Bairro` VARCHAR(50) NULL,
  `Telefone` VARCHAR(14) NULL,
  `Celular` VARCHAR(14) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `DataNascimento` DATE NULL,
  PRIMARY KEY(`CdCliente`),
  UNIQUE KEY(`CpfCnpj`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;

DROP TABLE IF EXISTS `CONTRATO`;
CREATE TABLE IF NOT EXISTS `CONTRATO` (
  `CdContrato` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `CdCliente` INTEGER UNSIGNED NOT NULL,
  `DescricaoEvento` VARCHAR(200) NOT NULL,
  `DataCadastro` DATETIME NOT NULL,
  `DataEvento` DATETIME NOT NULL,
  `DataAceite` DATETIME NULL,
  `Documento` BLOB NULL,
  `ValorContrato` DECIMAL(19,4) NULL,
  PRIMARY KEY(`CdContrato`),
  FOREIGN KEY(`CdCliente`)
    REFERENCES CLIENTE(`CdCliente`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;

CREATE TABLE IF NOT EXISTS `TIPO_USUARIO` (
  `CdTipoUsuario` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(20) NOT NULL,
  PRIMARY KEY(`CdTipoUsuario`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;

INSERT INTO `TIPO_USUARIO` (`CdTipoUsuario`, `Descricao`) VALUES
(1, 'Administrador'),
(2, 'Funcionario'),
(3, 'Cliente');

DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `CdUsuario` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `CdTipoUsuario` INTEGER UNSIGNED DEFAULT NULL,
  `NomeUsuario` VARCHAR(50) DEFAULT NULL,
  `Email` VARCHAR(50) DEFAULT NULL,
  `Senha` VARCHAR(128) NULL,
  PRIMARY KEY(`CdUsuario`),
  UNIQUE KEY(`NomeUsuario`),
  UNIQUE KEY(`Email`)
  FOREIGN KEY(`CdTipoUsuario`)
    REFERENCES TIPO_USUARIO(`CdTipoUsuario`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;

INSERT INTO `USUARIO` (`CdUsuario`, `CdTipoUsuario`, `NomeUsuario`, `Email`, `Senha`) VALUES
(1, 1,'Admin', 'admin@organizzaestudio.com','Admin');

DROP TABLE IF EXISTS `IMAGEM`;
CREATE TABLE IF NOT EXISTS `IMAGEM` (
  `CdImagem` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `CdFuncionario` INTEGER UNSIGNED NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Caminho` VARCHAR(200) NOT NULL,
  `Tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY(`CdImagem`),
  FOREIGN KEY(`CdFuncionario`)
    REFERENCES FUNCIONARIO(`CdFuncionario`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;


CREATE TABLE IF NOT EXISTS `CONTRATO_SERVICO` (
  `CdContratoServico` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `CdContrato` INTEGER UNSIGNED NOT NULL,
  `CdServico` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(`CdContratoServico`),
  FOREIGN KEY(`CdServico`)
    REFERENCES SERVICO(`CdServico`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(`CdContrato`)
    REFERENCES CONTRATO(`CdContrato`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;

CREATE TABLE IF NOT EXISTS `CONTRATO_IMAGEM` (
  `CdContratoImagem` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `CdImagem` INTEGER UNSIGNED NOT NULL,
  `CdContrato` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(`CdContratoImagem`),
  FOREIGN KEY(`CdContrato`)
    REFERENCES CONTRATO(`CdContrato`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(`CdImagem`)
    REFERENCES IMAGEM(`CdImagem`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=11 ;


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
